name: GitHub Traffic (Clones + Views)

on:
  schedule:
    - cron: "0 0 * * *"   # runs once per day
  workflow_dispatch:       # allow manual trigger

jobs:
  update-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.SECRET_TOKEN }}" | gh auth login --with-token

      # --- CLONES ---
      - name: Fetch clone stats
        run: |
          curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones \
            > clones.json

      - name: Update clone gist
        run: |
          content=$(cat clones.json | jq -c .)
          echo '{"description":"'"${{ github.repository }}"' clone statistics","files":{"clone.json":{"content":'"$content"'}}}' > post.json
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            -d @post.json \
            https://api.github.com/gists/${{ secrets.CLONE_GIST_ID }}

      # --- VIEWS ---
      - name: Fetch view stats
        run: |
          curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/traffic/views \
            > views.json

      - name: Update view gist
        run: |
          content=$(cat views.json | jq -c .)
          echo '{"description":"'"${{ github.repository }}"' view statistics","files":{"views.json":{"content":'"$content"'}}}' > post.json
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            -d @post.json \
            https://api.github.com/gists/${{ secrets.VIEW_GIST_ID }}
