name: GitHub Clone Count Badge

on:
  schedule:
    - cron: "0 0 * * *"   # runs once per day
  workflow_dispatch:       # allow manual trigger

jobs:
  update-clones:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.SECRET_TOKEN }}" | gh auth login --with-token

      - name: Fetch latest clone stats
        run: |
          curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones \
            > clone.json

      - name: Update gist with clone.json
        run: |
          gist_id=${{ secrets.GIST_ID }}
          content=$(cat clone.json | jq -c .)
          echo '{"description":"'"${{ github.repository }}"' clone statistics","files":{"clone.json":{"content":'"$content"'}}}' > post.json
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            -d @post.json \
            https://api.github.com/gists/$gist_id
